# Generated by Django 4.0.6 on 2022-07-31 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_documents_downloadlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='downloadlink',
            name='expired',
        ),
        migrations.RemoveField(
            model_name='downloadlink',
            name='iv',
        ),
        migrations.RemoveField(
            model_name='downloadlink',
            name='pwd',
        ),
        migrations.RemoveField(
            model_name='downloadlink',
            name='salt',
        ),
        migrations.RemoveField(
            model_name='downloadlink',
            name='url',
        ),
        migrations.AddField(
            model_name='downloadlink',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='downloadlink',
            name='status',
            field=models.CharField(choices=[('not active', 'Not Active'), ('active', 'Active')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='downloadlink',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
