# Generated by Django 4.0.6 on 2022-08-03 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_documents_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadlink',
            name='user',
        ),
    ]
