# Generated by Django 4.0.6 on 2022-08-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_documents_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='file_type',
            field=models.CharField(blank=True, default='', editable=False, max_length=10, null=True),
        ),
    ]
