# Generated by Django 4.0.6 on 2022-08-05 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_downloadlink_domain_downloadlink_ip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadlink',
            name='session',
        ),
    ]
