# Generated by Django 4.0.6 on 2022-08-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_remove_downloadlink_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadlink',
            name='enc_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
