# Generated by Django 4.0.6 on 2023-01-12 08:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.SmallIntegerField(choices=[(1, 'Facebook'), (2, 'Twitter'), (3, 'Pinterest'), (4, 'Youtube'), (5, 'Instagram')])),
                ('link', models.URLField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pages',
            name='kind',
            field=models.CharField(choices=[('about us', 'About Us'), ('send writing', 'Send Writing')], default=None, max_length=20),
            preserve_default=False,
        ),
    ]
