# Generated by Django 4.0.6 on 2023-01-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_socialmedia_pages_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='kind',
            field=models.CharField(choices=[('about us', 'About Us'), ('send writing', 'Send Writing'), ('contact us', 'Contact Us')], max_length=20),
        ),
    ]
